unit:
    path:     /
    defaults: { _controller: "CodersgroupSpendingRegistryBundle:Unit:index" }

unit_new:
    path:     /new
    defaults: { _controller: "CodersgroupSpendingRegistryBundle:Unit:new" }

unit_create:
    path:     /create
    defaults: { _controller: "CodersgroupSpendingRegistryBundle:Unit:create" }
    requirements: { _method: post }

unit_edit:
    path:     /{id}/edit
    defaults: { _controller: "CodersgroupSpendingRegistryBundle:Unit:edit" }

unit_update:
    path:     /{id}/update
    defaults: { _controller: "CodersgroupSpendingRegistryBundle:Unit:update" }
    requirements: { _method: post|put }

unit_delete:
    path:     /{id}/delete
    defaults: { _controller: "CodersgroupSpendingRegistryBundle:Unit:delete" }
    requirements: { _method: post|delete }
