parameters:
#    codersgroup_user.example.class: Codersgroup\Bundle\UserBundle\Example

services:
#    codersgroup_user.example:
#        class: %codersgroup_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
