parameters:
#    codersgroup_spending_registry.example.class: Codersgroup\Bundle\SpendingRegistryBundle\Example

services:
#    codersgroup_spending_registry.example:
#        class: %codersgroup_spending_registry.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
